# https://jekyllrb.com/docs/configuration/options/

# Server
destination: _site
keep_files:
  - assets/app
  - assets/css
  - assets/js
  - assets/data
  - assets/img
  - assets/options
  - assets/plugins
host: "localhost"
baseurl: ""
plugins: 
  - jekyll-assets